ToDoApp/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/urls.py
from django.conf.urls import url
from django.urls import path
from app import views

urlpatterns = [
  path('', views.home, name='home'),
  path('add_todo', views.add_todo, name='add_todo'),
  path('complete_todo/<int:book_id>', views.complete_todo),
  path('<int:task_id>/task_completed', views.task_completed, name='task_completed'),
  path('completed_tasks', views.completed_tasks),
  path('add_sub_task', views.add_sub_task),
  path('edit_sub_task/<int:sub_task_id>', views.edit_sub_task),
  path('frm_edit_sub_task', views.frm_edit_sub_task)
]

app/models.py
from django.db import models


class TaskType(models.Model):
    type_of_task = models.CharField(max_length=200)


class ToDo(models.Model):
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE, default=1)
    added_date = models.DateTimeField(null=False)
    text = models.CharField(max_length=200)
    is_completed = models.BooleanField(default=False)
    completed_date = models.DateTimeField(null=True)
    note = models.CharField(max_length=500, blank=True)


class SubTask(models.Model):
    task_id = models.ForeignKey(ToDo, on_delete=models.CASCADE)
    task_text = models.CharField(max_length=200)
    task_note = models.CharField(max_length=200, blank=True)
    task_status = models.CharField(max_length=20)

app/views.py
from django.shortcuts import render
from django.utils import timezone
from . import models
from django.http import HttpResponseRedirect


# Create your views here.
def home(request):
    books = models.ToDo.objects.filter(is_completed=False).order_by('-added_date')
    stuff_for_frontend = {
        'addedTasks': books,
        'taskTypes': models.TaskType.objects.all().order_by('type_of_task')
    }
    return render(request, 'app/index.html', stuff_for_frontend)


def add_todo(request):
    text_content = request.POST["content"]
    task_type = models.TaskType.objects.get(pk= request.POST["task_type"])
    models.ToDo.objects.create(text=text_content, task_type=task_type, added_date=timezone.datetime.now())
    return HttpResponseRedirect('/')


def complete_todo(request, book_id):
    stuff_for_frontend = {
        'task': models.ToDo.objects.get(id=book_id)
    }
    return render(request, 'app/completetask.html', stuff_for_frontend)


def task_completed(request, task_id):
    task = models.ToDo.objects.get(id=task_id)
    task.is_completed = True
    task.completed_date = timezone.datetime.now()
    task.note = request.POST['complete_note']
    task.save()
    return HttpResponseRedirect('/')


def completed_tasks(request):
    stuff_for_frontend = {
        'tasks': models.ToDo.objects.filter(is_completed=True).order_by('completed_date')
    }
    return render(request, 'app/completedtasks.html', stuff_for_frontend)


def add_sub_task(request):
    task = models.ToDo.objects.get(id=request.POST['mainTaskId'])
    models.SubTask.objects.create(task_id=task, task_text=request.POST['subTaskText'], task_status='Raised')
    return HttpResponseRedirect('/')


def edit_sub_task(request, sub_task_id):
    subTask = models.SubTask.objects.get(id=sub_task_id)
    stuff_for_frontend = {
        'subTask': subTask
    }
    return render(request, 'app/edit_sub_task.html', stuff_for_frontend)


def frm_edit_sub_task(request):
    subtask = models.SubTask.objects.get(id=request.POST['id'])
    subtask.task_status = request.POST['task_status']
    subtask.task_note = request.POST['complete_note']
    subtask.task_text = request.POST['task_test']
    subtask.save()
    return HttpResponseRedirect('/')

templates/app/completedtasks.html
{% extends "base.html" %}

{% block content %}
    <div class="col-sm-12 mt-4">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-10"><h2>Task Completed: {{ tasks.count }}</h2></div>
                    <div class="col-sm-2 text-right"><a href="/" type="button" class="btn btn-sm"><i
                            class="material-icons">add_box</i> Add New Tasks</a>
                    </div>
                </div>
            </div>
            <div class="accordion" id="accordionExample">
                {% for task in tasks %}
                    <div class="card">
                        <div class="card-header" id="heading{{ task.id }}">
                            <h2 class="mb-0">
                                <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                        data-target="#collapse{{ task.id }}" aria-expanded="false"
                                        aria-controls="collapseTwo">
                                    <b>{{ task.text }}</b>
                                </button>
                            </h2>
                        </div>
                        <div id="collapse{{ task.id }}" class="collapse" aria-labelledby="heading{{ task.id }}"
                             data-parent="#accordionExample">
                            <div class="card-body">
                                {% for st in task.subtask_set.all %}
                                    {% if st.task_status == 'Done' %}
                                        <span style="">&emsp;&emsp;&emsp;--- <strike>{{ st.task_text }}</strike> ({{ st.task_status }})</span>
                                    {% elif st.task_status == 'Started' %}
                                        <span style="color: darkgreen;">&emsp;&emsp;&emsp;--- {{ st.task_text }} ({{ st.task_status }})</span>
                                    {% else %}
                                        <span style="color: darkblue;">&emsp;&emsp;&emsp;--- {{ st.task_text }} ({{ st.task_status }})</span>
                                    {% endif %}
                                    <br />
                                {% endfor %}
                            <br/>
                                <span>Added On: {{ task.added_date }}</span><br/>
                                <span>Completed On: {{ task.completed_date }}</span><br/><br/>
                                <p>{{ task.note | linebreaks }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>



{% endblock %}

templates/app/completetask.html
{% extends "base.html" %}

{% block content %}

    <div class="col-sm-12 mt-4">
        <div class="card">
            <div class="card-header">
                <h2>Task Completed: <font color="green">{{ task.text }}</font></h2>
            </div>
            <form action="{% url 'task_completed' task.id %}" method="post">
                {% csrf_token %}
                <textarea class="form-control" rows="8" name="complete_note" placeholder="Completion note" required></textarea>
                <br />
                <div class="text-center">
                <button type="submit" class="btn btn-primary mb-2 text-right"><i class="material-icons">save</i> Task Completed</button>&nbsp;
                    <a href="/" type="button" class="btn btn-info mb-2 text-right">Back to Front <i class="material-icons">forward</i></a>
                    </div>
            </form>
        </div>
    </div>

{% endblock content %}

templates/app/edit_sub_task.html
{% extends "base.html" %}

{% block content %}

    <div class="col-sm-12 mt-4">
        <div class="card">
            <div class="card-header">
                <h2>Edit Sub Task: <font color="green">{{ subTask.task_text }}</font></h2>
            </div>

            <div class="card-body">
                <form action="/frm_edit_sub_task" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">Status</span>
                                </div>
                                <input type="hidden" name="id" value="{{ subTask.id }}">
                                <select name="task_status" id="task_status" class="form-control col-sm-6 text-center">
                                    <option value="Raised">Raised</option>
                                    <option value="Started">Started</option>
                                    <option value="Done">Done</option>
                                </select>
                            </div>
                            <br/>
                            <button type="submit" class="btn btn-primary mb-2 text-right"><i
                                    class="material-icons">save</i> Save Data
                            </button>&nbsp;
                            <a href="/" type="button" class="btn btn-info mb-2 text-right">Back to Front <i
                                    class="material-icons">forward</i></a>
                        </div>
                        <div class="col-sm-9">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">Sun Task Name</span>
                                </div>
                                <input type="text" name="task_test" value="{{ subTask.task_text }}" required class="form-control">
                            </div>
                        <textarea class="form-control" rows="8" name="complete_note" placeholder="Sub task note">{{ subTask.task_note }}</textarea>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="application/javascript">
        $(document).ready(function () {
            $("#task_status").val('{{ subTask.task_status }}');
        })
    </script>

{% endblock %}

templates/app/index.html
{% extends "base.html" %}
{% load app_extras %}

{% block content %}
    <div class="row mt-4">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h2>Add To Do Item</h2>
                </div>
                <div class="card-body">
                    <form action="add_todo" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="basic-addon1">Task For</span>
                                    </div>
                                    <select name="task_type" class="form-control">
                                        {% for type in taskTypes %}
                                            <option value={{ type.id }}>{{ type.type_of_task }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <input type="text" class="form-control mb-2 mr-sm-2" name="content"
                                       placeholder="type here..." required>
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-primary mb-2"><i class="material-icons">save</i>
                                    Save Task
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-10"><h2>Things to do: {{ addedTasks.count }}</h2></div>
                        <div class="col-sm-2 text-right"><a href="completed_tasks" type="button" class="btn btn-sm"><i
                                class="material-icons">done_all</i> Completed Tasks</a></div>
                    </div>
                </div>
                <ul class="list-group">
                    {% for todo in addedTasks %}
                        <li class="list-group-item" aria-disabled="true" style="font-weight: bold"><span
                                style="color: brown">{{ todo.text }}
                            ({{ todo.task_type.type_of_task }})</span>
                            <div class="float-right">
                                <div class="progress mb-2">
                                    <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25"
                                         aria-valuemin="0" aria-valuemax="100">25%
                                    </div>
                                </div>
                                <a href="#" data-id="{{ todo.id }}"
                                   class="btn btn-sm btn-success addTaskModalOpener"><i
                                        class="material-icons">add_box</i> Sub Task</a>
                                <a href="#/{{ todo.id }}"
                                   class="btn btn-sm btn-success"><i class="material-icons">edit</i> Edit</a>
                                <a href="complete_todo/{{ todo.id }}"
                                   class="btn btn-sm btn-success"><i class="material-icons">done</i> Completed</a>
                            </div>
                            <br/>
                            {% for st in todo.subtask_set.all %}
                                <br/>
                                {% if st.task_status == 'Done' %}
                                    <span style="">&emsp;&emsp;&emsp;--- <strike>{{ st.task_text }}</strike> ({{ st.task_status }})</span>
                                {% elif st.task_status == 'Started' %}
                                    <span style="color: darkgreen;">&emsp;&emsp;&emsp;--- {{ st.task_text }} ({{ st.task_status }})</span>
                                    <a href="edit_sub_task/{{ st.id }}"><i class="material-icons">edit</i></a>
                                {% else %}
                                    <span style="color: darkblue;">&emsp;&emsp;&emsp;--- {{ st.task_text }} ({{ st.task_status }})</span>
                                    <a href="edit_sub_task/{{ st.id }}"><i class="material-icons">edit</i></a>
                                {% endif %}
                            {% endfor %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="modal fade" id="addSubTaskModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form action="add_sub_task" method="post">
                {% csrf_token %}
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add New Sub Task</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <input type="hidden" id="mainTaskId" name="mainTaskId">
                            <input type="text" class="form-control" id="subTaskText" name="subTaskText"
                                   placeholder="type here..." required>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary"><i class="material-icons">save</i>Save Sub Task
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


{% endblock content %}

{% block scripts %}
    <script type="application/javascript">
        $(document).ready(function () {

        });
        $(".addTaskModalOpener").on("click", function () {
            var taskId = $(this).data('id');
            $("#addSubTaskModal").modal('show');
            $("#mainTaskId").val(taskId);
        });
    </script>
{% endblock scripts %}

templates/base.html
{% load staticfiles %}
        <!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Moloy's To Do App</title>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Moloy's To Do Application</a>
  <!-- Navbar content -->
</nav>
<div class="container">
  {% block content %}{% endblock content %}
</div>
<!-- Footer -->
<footer class="footer mt-2">
    <div class="card">
        <div class="card-header bg-info text-center bg-dark text-white" style="padding: .25rem 1.25rem">
            <p style="margin-bottom: 0rem">Developed using Python(3.7.4),  Django (2.2.6), MySql</p>
            <h3 style="margin-bottom: 0rem !important">Developed by Malai Joti Adhikary &copy;</h3>
        </div>
    </div>
</footer>
<!-- Footer -->
</body>

<style type="text/css">
    .material-icons {
    vertical-align: middle;
}
.list-group-item{
    padding: .25rem 1.25rem;
}
</style>
</html>

{% block scripts %}{% endblock scripts %}